import { Box } from '@mui/material';

const MOCK_SVERILOG = `// Auto-generated SystemVerilog for CGRA (4x4, VectorCGRA)
// Generated by cgra-flow

module cgra_top #(
  parameter NUM_TILE_ROWS = 4,
  parameter NUM_TILE_COLS = 4,
  parameter DATA_WIDTH     = 32,
  parameter CGRA_ID        = 0
)(
  input  logic                  clk,
  input  logic                  reset,
  input  logic [DATA_WIDTH-1:0] recv_waddr [NUM_TILE_ROWS-1:0],
  input  logic [DATA_WIDTH-1:0] recv_wdata [NUM_TILE_ROWS-1:0],
  input  logic                  recv_wen   [NUM_TILE_ROWS-1:0],
  output logic [DATA_WIDTH-1:0] send_rdata [NUM_TILE_COLS-1:0]
);

  // Internal wiring between tiles
  logic [DATA_WIDTH-1:0] tile_north [NUM_TILE_ROWS-1:0][NUM_TILE_COLS-1:0];
  logic [DATA_WIDTH-1:0] tile_south [NUM_TILE_ROWS-1:0][NUM_TILE_COLS-1:0];
  logic [DATA_WIDTH-1:0] tile_east  [NUM_TILE_ROWS-1:0][NUM_TILE_COLS-1:0];
  logic [DATA_WIDTH-1:0] tile_west  [NUM_TILE_ROWS-1:0][NUM_TILE_COLS-1:0];

  genvar r, c;
  generate
    for (r = 0; r < NUM_TILE_ROWS; r++) begin : tile_row
      for (c = 0; c < NUM_TILE_COLS; c++) begin : tile_col
        pe_tile #(
          .DATA_WIDTH(DATA_WIDTH),
          .TILE_ID(r * NUM_TILE_COLS + c)
        ) u_tile (
          .clk     (clk),
          .reset   (reset),
          .in_north(tile_north[r][c]),
          .in_south(tile_south[r][c]),
          .in_east (tile_east[r][c]),
          .in_west (tile_west[r][c]),
          .out_north(tile_north[(r-1+NUM_TILE_ROWS)%NUM_TILE_ROWS][c]),
          .out_south(tile_south[(r+1)%NUM_TILE_ROWS][c]),
          .out_east (tile_east[r][(c+1)%NUM_TILE_COLS]),
          .out_west (tile_west[r][(c-1+NUM_TILE_COLS)%NUM_TILE_COLS])
        );
      end
    end
  endgenerate

  // SPM read interface
  always_comb begin
    for (int i = 0; i < NUM_TILE_COLS; i++) begin
      send_rdata[i] = tile_south[NUM_TILE_ROWS-1][i];
    end
  end

endmodule
`;

function SverilogPanel() {
  return (
    <Box
      component="pre"
      sx={{
        m: 0,
        p: 2,
        background: '#1e1e1e',
        color: '#d4d4d4',
        fontFamily: 'monospace',
        fontSize: '0.8rem',
        lineHeight: 1.6,
        overflow: 'auto',
        maxHeight: '400px',
        borderRadius: 1,
        whiteSpace: 'pre',
      }}
    >
      {MOCK_SVERILOG}
    </Box>
  );
}

export default SverilogPanel;
