export PLATFORM               = asap7
export DESIGN_NAME            = CgraTemplateRTL
# VERILOG_FILES is supplied at make time: make VERILOG_FILES=/layout/design_sv2v.v
export SDC_FILE               = /opt/orfs-flow/designs/asap7/CgraTemplateRTL/constraint.sdc
export SYNTH_HIERARCHICAL     = 1
export RTLMP_FLOW             = True
export ENABLE_DPO             = True
export CORE_UTILIZATION       = 15
export CORE_ASPECT_RATIO      = 1
export GPL_ROUTABILITY_DRIVEN = 1
export CORE_MARGIN            = 5
export PLACE_DENSITY          = 0.3
export TNS_END_PERCENT        = 100
export CTS_BUF_CELL           = BUFx8_ASAP7_75t_R
export DETAILED_ROUTE_ARGS    = -bottom_routing_layer M2 -top_routing_layer M9 -save_guide_updates -verbose 1 -droute_end_iter 45
export RECOVER_POWER          = 50
export MIN_ROUTING_LAYER      = M2
export MAX_ROUTING_LAYER      = M9
export GLOBAL_ROUTE_ARGS      = -congestion_iterations 40 -verbose
export REMOVE_CELLS_FOR_EQY   = TAPCELL*
export SKIP_GATE_CLONING      = 1
export GPL_TIMING_DRIVEN      = 0
